version: '3.9'

services:
  api:
    build: ~
    image: ~
    volumes:
      - ./apps/api/src:/app/apps/api/src
    command: sh -c "npx prisma migrate deploy && pnpm run start:dev"
    environment:
      NODE_ENV: development

  web:
    build: ~
    image: ~
    volumes:
      - ./apps/web/src:/app/apps/web/src
    command: pnpm dev
